{
  "openapi": "3.1.0",
  "info": {
    "version": "12.74.3",
    "title": "AEM Admin API",
    "description": "AEM Admin API is used to manage the lifecycle of content and code.",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "servers": [
    {
      "url": "https://admin.hlx.page"
    }
  ],
  "tags": [
    {
      "name": "status",
      "description": "Status operations"
    },
    {
      "name": "publish",
      "description": "Publish operations"
    },
    {
      "name": "preview",
      "description": "Preview operations"
    },
    {
      "name": "code",
      "description": "Code bus operations"
    },
    {
      "name": "cache",
      "description": "Cache operations"
    },
    {
      "name": "index",
      "description": "Index operations"
    },
    {
      "name": "authentication",
      "description": "The API uses your existing Identity Provider (IDP) to authenticate users with administrative access. The general flow is that you open `/login` in a browser, select the IDP you want to use, and then are redirected to the IDP login page. After successful login, you are redirected back to the Admin API with an auth token in the response cookie (`auth_token`). This token is then used to authenticate all subsequent requests. <br><br> Alternatively, you can provide an `authoriza[...]"
    },
    {
      "name": "sitemap",
      "description": "Sitemap operations"
    },
    {
      "name": "job",
      "description": "Job operations"
    },
    {
      "name": "log",
      "description": "Log operations"
    },
    {
      "name": "snapshot",
      "description": "Snapshot operations"
    },
    {
      "name": "orgConfig",
      "x-displayName": "Org Config",
      "description": "Org Config operations"
    },
    {
      "name": "siteConfig",
      "x-displayName": "Site Config",
      "description": "Please note that most of the configuration objects that have an explicit schema can also be addressed directly, even if not listed in this documentation. <br> For example the production CDN configuration can be managed via the <code>/config/{org}/sites/{site}/cdn/prod.json</code> endpoint.\n"
    },
    {
      "name": "profileConfig",
      "x-displayName": "Profile Config",
      "description": "Please note that most of the configuration objects that have an explicit schema can also be addressed directly, even if not listed in this documentation. <br> For example the production CDN configuration can be managed via the <code>/config/{org}/profiles/default-profile/cdn/prod.json</code> endpoint.\n"
    },
    {
      "name": "indexConfig",
      "x-displayName": "Index Config",
      "description": "A configuration containing one or more index definitions.\n"
    },
    {
      "name": "sitemapConfig",
      "x-displayName": "Sitemap Config",
      "description": "A configuration containing one or more sitemap definitions.\n"
    }
  ],
  "paths": {
    "/status/{org}/{site}/{ref}/{path}": {
      "get": {
        "operationId": "status",
        "tags": [
          "status"
        ],
        "summary": "General status",
        "description": "Returns the overall status of the respective resource. (If the `?edit=auto` query param is set, this requires a call to your content source see https://www.aem.live/docs/limits#rate-limits-number-of-preview-operations-per-time)",
        "security": [
          {},
          {
            "AuthCookie": [
              "preview:read",
              "live:read",
              "code:read",
              "edit:read"
            ]
          }
        ]
      }
    },
    "/status/{org}/{site}/{ref}/*": {
      "post": {
        "operationId": "bulkStatus",
        "tags": [
          "status"
        ],
        "summary": "Start a bulk status job",
        "description": "Fetches the status of all resources specified in the `paths` property in the payload. If a path ends with `/*`, it is assumed to be a folder and is recursively processed.<br><br> The response will contain the folliowing information about a resource: `path`, `sourceLastModified`, `previewLastModified` and `publishLastModified`. It is possible to filter the information returned, by passing a combination of `edit`, `preview` and `live` in the `select` property in the payload[...]",
        "security": [
          {},
          {
            "AuthCookie": [
              "edit:list",
              "preview:list",
              "live:list"
            ]
          }
        ]
      }
    },
    "/live/{org}/{site}/{ref}/{path}": {
      "get": {
        "operationId": "getPublishStatus",
        "tags": [
          "publish"
        ],
        "summary": "Publish Status",
        "description": "Returns the publish status of the respective resource.",
        "security": [
          {
            "AuthCookie": [
              "live:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "publishResource",
        "tags": [
          "publish"
        ],
        "summary": "Publish a resource",
        "description": "Publish a resource by copying the resource content from the `preview` content-bus partition to the `live` content-bus partition. It additionally purges the _live_ cdn and the _byo_ cdn, if configured.\n",
        "security": [
          {
            "AuthCookie": [
              "preview:read",
              "live:read",
              "live:write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "unpublishResource",
        "tags": [
          "publish"
        ],
        "summary": "Un-publish a resource",
        "description": "Un-publish a resource by deleting the content from from the `live` content-bus partition. It additionally purges the _live_ cdn and the _byo_ cdn, if configured.\n",
        "security": [
          {
            "AuthCookie": [
              "live:read",
              "live:delete"
            ]
          }
        ]
      }
    },
    "/live/{org}/{site}/{ref}/*": {
      "post": {
        "operationId": "bulkPublish",
        "tags": [
          "publish"
        ],
        "summary": "Start a bulk publish job",
        "description": "Updates live resources specified in the `paths` property in the payload.<br> By default, only new and modified resources are updated, unless the `forceUpdate` property is set to `true`.<br> Note that configuration files, like `/.helix/config` or `redirects.json`, are always ignored during bulk publish.<br> Note that the bulk publish is performed asynchronously and this request will return information to the created job.\n",
        "security": [
          {
            "AuthCookie": [
              "preview:list",
              "preview:read",
              "preview:write"
            ]
          }
        ]
      }
    },
    "/preview/{org}/{site}/{ref}/{path}": {
      "get": {
        "operationId": "previewStatus",
        "tags": [
          "preview"
        ],
        "summary": "Preview status",
        "description": "Returns the preview status of the respective resource.",
        "security": [
          {
            "AuthCookie": [
              "preview:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updatePreview",
        "tags": [
          "preview"
        ],
        "summary": "Update preview",
        "description": "Updates the preview resource by fetching the latest content from the content providers (e.g. sharepoint, google docs, BYOM) and storing it in `preview`.\n",
        "security": [
          {
            "AuthCookie": [
              "edit:read",
              "preview:read",
              "preview:write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deletePreview",
        "tags": [
          "preview"
        ],
        "summary": "Delete preview",
        "description": "Deletes a preview resource from the `preview` partition in the content-bus..\n",
        "security": [
          {
            "AuthCookie": [
              "preview:read",
              "preview:delete"
            ]
          }
        ]
      }
    },
    "/preview/{org}/{site}/{ref}/*": {
      "post": {
        "operationId": "bulkPreview",
        "tags": [
          "preview"
        ],
        "summary": "Start a bulk preview job",
        "description": "Updates preview resources specified in the `paths` property in the payload. If a path ends with `/*`, it is assume to be folder and is recursively previewed.<br> By default, only new and modified resources are updated, unless the `forceUpdate` property is set to `true`.<br> Note that configuration files, like `/.helix/config` or `redirects.json`, are always ignored during bulk preview.<br> Note that the bulk preview is performed asynchronously and this request will return[...]",
        "security": [
          {
            "AuthCookie": [
              "edit:read",
              "edit:list",
              "preview:read",
              "preview:write"
            ]
          }
        ]
      }
    },
    "/code/{owner}/{repo}/{ref}/{path}": {
      "get": {
        "operationId": "codeStatus",
        "tags": [
          "code"
        ],
        "summary": "Code bus status",
        "description": "Returns the code bus status of the respective resource.",
        "security": [
          {},
          {
            "AuthCookie": [
              "code:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateCode",
        "tags": [
          "code"
        ],
        "summary": "Update code",
        "description": "Updates the code-bus resource by fetching the latest content from github and storing it in the code-bus. If the last path segment is a `*`, it will recursively update the code-bus with the respective github tree (directory). It additionally purges the _live_ cdn and the _byo_ cdn, if configured.\n",
        "security": [
          {},
          {
            "AuthCookie": [
              "code:read",
              "code:write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteCode",
        "tags": [
          "code"
        ],
        "summary": "Delete code",
        "description": "Deletes a code resource from the code-bus It additionally purges the _live_ cdn and the _byo_ cdn, if configured.\n",
        "security": [
          {
            "AuthCookie": [
              "code:read",
              "delete:code"
            ]
          }
        ]
      }
    },
    "/code/{owner}/{repo}/{ref}": {
      "post": {
        "operationId": "batchCode",
        "tags": [
          "code"
        ],
        "summary": "Batch update code",
        "description": "Processes a change event and updates the code-bus accordingly. It additionally purges the _live_ cdn and the _byo_ cdn, if configured.\n",
        "security": [
          {},
          {
            "AuthCookie": [
              "code:read",
              "code:write"
            ]
          }
        ]
      }
    },
    "/cache/{org}/{site}/{ref}/{path}": {
      "post": {
        "operationId": "purgeCache",
        "tags": [
          "cache"
        ],
        "summary": "Purge live cache",
        "description": "Purges the resource from the respective _live_ cdn. It optionally invokes the _byo_ cdn purging hook, if configured.\n",
        "security": [
          {},
          {
            "AuthCookie": [
              "cache:write"
            ]
          }
        ]
      }
    },
    "/index/{org}/{site}/{ref}/{path}": {
      "get": {
        "operationId": "getIndexStatus",
        "tags": [
          "index"
        ],
        "summary": "Index Status",
        "description": "Returns the index status of the respective resource.",
        "security": [
          {},
          {
            "AuthCookie": [
              "index:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "indexResource",
        "tags": [
          "index"
        ],
        "summary": "Re-index a resource.",
        "description": "Index a resource. If the last path segment is a `*`, it will recursively reindex all published resources below that sub tree.\n",
        "security": [
          {},
          {
            "AuthCookie": [
              "index:write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "indexRemovePage",
        "tags": [
          "index"
        ],
        "summary": "Remove a resource from the index.",
        "description": "Removes a resource from the index.\n",
        "security": [
          {},
          {
            "AuthCookie": [
              "index:write"
            ]
          }
        ]
      }
    },
    "/login": {
      "get": {
        "operationId": "login",
        "tags": [
          "authentication"
        ],
        "summary": "Login Selection",
        "description": "Provides a selection of available IDP logins",
        "security": [
          {}
        ]
      }
    },
    "/login/{org}/{site}/{ref}": {
      "get": {
        "operationId": "login-repo",
        "tags": [
          "authentication"
        ],
        "summary": "Auto login",
        "description": "Redirects to IDP corresponding the project setup",
        "security": [
          {}
        ]
      }
    },
    "/logout": {
      "get": {
        "operationId": "logout",
        "tags": [
          "authentication"
        ],
        "summary": "Logout",
        "description": "Logs out the current session and redirects to the login screen",
        "security": [
          {}
        ]
      }
    },
    "/profile": {
      "get": {
        "operationId": "profile",
        "tags": [
          "authentication"
        ],
        "summary": "Profile information",
        "description": "Display profile information",
        "security": [
          {},
          {
            "AuthCookie": [
              "profile:read"
            ]
          }
        ]
      }
    },
    "/sitemap/{org}/{site}/{ref}/{path}": {
      "post": {
        "operationId": "generateSitemap",
        "tags": [
          "sitemap"
        ],
        "summary": "Generates a sitemap",
        "description": "Generates a sitemap. The path specified should be the destination path of a sitemap.\n",
        "security": [
          {}
        ]
      }
    },
    "/job/{org}/{site}/{ref}/{topic}": {
      "get": {
        "operationId": "getJobList",
        "tags": [
          "job"
        ],
        "summary": "Job List",
        "description": "Returns the job list of jobs",
        "security": [
          {
            "AuthCookie": [
              "job:list"
            ]
          }
        ]
      }
    },
    "/job/{org}/{site}/{ref}/{topic}/{jobName}": {
      "get": {
        "operationId": "getJob",
        "tags": [
          "job"
        ],
        "summary": "Job Status",
        "description": "Returns the job status",
        "security": [
          {
            "AuthCookie": [
              "job:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "stopJob",
        "tags": [
          "job"
        ],
        "summary": "Stop job",
        "description": "Stops a job.",
        "security": [
          {
            "AuthCookie": [
              "job:read",
              "job:write"
            ]
          }
        ]
      }
    },
    "/job/{org}/{site}/{ref}/{topic}/{jobName}/details": {
      "get": {
        "operationId": "getJobDetails",
        "tags": [
          "job"
        ],
        "summary": "Job Status Details",
        "description": "Returns the job status",
        "security": [
          {
            "AuthCookie": [
              "job:read"
            ]
          }
        ]
      }
    },
    "/log/{org}/{site}/{ref}": {
      "get": {
        "operationId": "getLogs",
        "tags": [
          "log"
        ],
        "summary": "Returns logs",
        "description": "Returns logs for a project. If there are more logs for the timespan specified, there will be a `next` link in the response to load the next batch.\n",
        "security": [
          {
            "AuthCookie": [
              "log:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "addLogs",
        "tags": [
          "log"
        ],
        "summary": "Add logs",
        "description": "Add logs to a project. The body should be in JSON format and contain an array called `entries`.\n",
        "security": [
          {
            "AuthCookie": [
              "log:read",
              "log:write"
            ]
          }
        ]
      }
    },
    "/snapshot/{org}/{site}/main": {
      "get": {
        "operationId": "listSnapshots",
        "tags": [
          "snapshot"
        ],
        "summary": "List snapshots",
        "description": "Returns a list of snapshot IDs",
        "security": [
          {
            "AuthCookie": [
              "snapshot:read"
            ]
          }
        ]
      }
    },
    "/snapshot/{org}/{site}/main/{snapshotId}": {
      "get": {
        "operationId": "getSnapshotManifest",
        "tags": [
          "snapshot"
        ],
        "summary": "Snapshot Manifest",
        "description": "Returns the snapshot manifest",
        "security": [
          {
            "AuthCookie": [
              "snapshot:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateSnapshotManifest",
        "tags": [
          "snapshot"
        ],
        "summary": "Update snapshot Manifest",
        "description": "Updates the Snapshot manifest and allows to lock or unlock the snapshot. Note that in order to lock the snapshot, the request role also needs to include the `preview:write` permission, and in order to unlock the snapshot, the `live:write` permission is needed.\n",
        "security": [
          {
            "AuthCookie": [
              "snapshot:write",
              "preview:write",
              "live:write"
            ]
          }
        ]
      }
    },
    "/snapshot/{org}/{site}/main/{snapshotId}/{path}": {
      "get": {
        "operationId": "getSnapshot",
        "tags": [
          "snapshot"
        ],
        "summary": "Snapshot status",
        "description": "Returns the snapshot status of the respective resource.",
        "security": [
          {
            "AuthCookie": [
              "snapshot:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "createSnapshot",
        "tags": [
          "snapshot"
        ],
        "summary": "Add resource to snapshot",
        "description": "Creates a snapshot of the specified resource and stores it in the preview partition below the `.snapshot/snapshotId` folder. If the path param ends with a `*`, a snapshot of the entire subtree is created. If the snapshot is locked, a `409` response is returned.\n",
        "security": [
          {
            "AuthCookie": [
              "snapshot:read",
              "snapshot:write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteSnapshot",
        "tags": [
          "snapshot"
        ],
        "summary": "Delete snapshot",
        "description": "Deletes a snapshot resource from the `preview` partition in the content-bus.  If the path param ends with a `*`, the entire subtree is deleted. If the snapshot is locked, a `409` response is returned.\n",
        "security": [
          {
            "AuthCookie": [
              "snapshot:read",
              "snapshot:delete"
            ]
          }
        ]
      }
    },
    "/snapshot/{org}/{site}/main/{snapshotId}/*": {
      "post": {
        "operationId": "bulkSnapshot",
        "tags": [
          "snapshot"
        ],
        "summary": "Start a bulk snapshot job",
        "description": "Add all resources specified in the `paths` property in the payload.<br> By default, only new and modified resources are updated, unless the `forceUpdate` property is set to `true`.<br> Note that the bulk snapshot is performed synchronously for arrays with fewer than 200 resources and no wildcard paths, and asynchronously otherwise.<br> Note that without the appropriate `application/json` content type header, the request will be treated as a wildcard add with no body, resu[...]",
        "security": [
          {
            "AuthCookie": [
              "snapshot:read",
              "snapshot:write"
            ]
          }
        ]
      }
    },
    "/snapshot/{org}/{site}/main/{snapshotId}/{path}?publish=true": {
      "post": {
        "operationId": "publishSnapshotResource",
        "tags": [
          "snapshot"
        ],
        "summary": "Publish snapshot resource",
        "description": "Publish snapshot resources by copying the resource content from the snapshot location to the `live` content-bus partition. It additionally purges the _live_ cdn and the _byo_ cdn, if configured. If the path param ends with a `*` the resources of the path's entire subtree is published.\n",
        "security": [
          {
            "AuthCookie": [
              "snapshot:read",
              "live:read",
              "live:write"
            ]
          }
        ]
      }
    },
    "/snapshot/{org}/{site}/main/{snapshotId}?publish=true": {
      "post": {
        "operationId": "publishSnapshot",
        "tags": [
          "snapshot"
        ],
        "summary": "Publish snapshot",
        "description": "Publish a snapshot by copying all resources from the snapshot location to the `live` content-bus partition. It additionally purges the _live_ cdn and the _byo_ cdn, if configured.\n",
        "security": [
          {
            "AuthCookie": [
              "snapshot:read",
              "live:read",
              "live:write"
            ]
          }
        ]
      }
    },
    "/snapshot/{org}/{site}/main/{snapshotId}?review=[request,approve,reject]": {
      "post": {
        "operationId": "reviewSnapshot",
        "tags": [
          "snapshot"
        ],
        "summary": "Change snapshot review state",
        "description": "Performs a review operation on the snapshot. `request` locks the snapshot; `approve` publishes all resources, clears, and unlocks the snapshot; `reject` unlocks the snapshot. All operations can contain an optional `message` parameter which will be included in logs and events.\n",
        "security": [
          {
            "AuthCookie": [
              "snapshot:read",
              "live:read",
              "live:write"
            ]
          }
        ]
      }
    },
    "/config/{org}.json": {
      "get": {
        "operationId": "getConfigOrg",
        "tags": [
          "orgConfig"
        ],
        "summary": "Read Organisation Config",
        "description": "Returns the organisation level configuration.",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateConfigOrg",
        "tags": [
          "orgConfig"
        ],
        "summary": "Update Organisation Config",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      },
      "put": {
        "operationId": "createConfigOrg",
        "tags": [
          "orgConfig"
        ],
        "summary": "Create Organisation Config",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteConfigOrg",
        "tags": [
          "orgConfig"
        ],
        "summary": "Delete Organisation Config",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/users.json": {
      "get": {
        "operationId": "listOrgUsers",
        "tags": [
          "orgConfig"
        ],
        "summary": "List Users",
        "description": "Returns the org users",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateOrgUser",
        "tags": [
          "orgConfig"
        ],
        "summary": "Create new org user",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/users/${id}.json": {
      "get": {
        "operationId": "readOrgUser",
        "tags": [
          "orgConfig"
        ],
        "summary": "Read user",
        "description": "Returns the user",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteOrgUser",
        "tags": [
          "orgConfig"
        ],
        "summary": "Delete user",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/secrets.json": {
      "get": {
        "operationId": "listOrgSecrets",
        "tags": [
          "orgConfig"
        ],
        "summary": "List org secrets",
        "description": "Returns the org secrets",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "createOrgSecret",
        "tags": [
          "orgConfig"
        ],
        "summary": "Create new org secret",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/secrets/${id}.json": {
      "get": {
        "operationId": "readOrgSecret",
        "tags": [
          "orgConfig"
        ],
        "summary": "Read secret",
        "description": "Returns the secret",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteOrgSecret",
        "tags": [
          "orgConfig"
        ],
        "summary": "Delete org secret",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/apiKeys.json": {
      "get": {
        "operationId": "listOrgApiKeys",
        "tags": [
          "orgConfig"
        ],
        "summary": "List org admin API keys",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "createOrgApiKey",
        "tags": [
          "orgConfig"
        ],
        "summary": "Create or import org admin API key",
        "description": "Creates a new admin API key for the org config. If a `jwt` parameter is given, it imports the given key. Please note that the added key can immediately be used and does not need to be added to the `access.admin.apiKeys` property.\n",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/apiKeys/${id}.json": {
      "get": {
        "operationId": "readOrgApiKey",
        "tags": [
          "orgConfig"
        ],
        "summary": "Read org admin API key",
        "description": "Returns the admin API key",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteOrgAdminApiKey",
        "tags": [
          "orgConfig"
        ],
        "summary": "Delete org admin API key",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/sites.json": {
      "get": {
        "operationId": "getConfigSites",
        "tags": [
          "siteConfig"
        ],
        "summary": "List Site Config",
        "description": "Returns the site level configuration names.",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      }
    },
    "/config/{org}/sites/{site}.json": {
      "get": {
        "operationId": "getConfigSite",
        "tags": [
          "siteConfig"
        ],
        "summary": "Read Site Config",
        "description": "Returns the site level configuration. If `migrate` is set to `true`, the configuration will be aggregated based on the legacy config (fstab, .helix/config.xlsx, etc).\n",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateConfigSite",
        "tags": [
          "siteConfig"
        ],
        "summary": "Update Site Config.",
        "description": "Stores new site configuration. If `migrate` is set to `true`, the configuration will be aggregated based on the legacy config (fstab, .helix/config.xlsx, etc) and will overwrite the existing configuration.",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      },
      "put": {
        "operationId": "createSiteSite",
        "tags": [
          "siteConfig"
        ],
        "summary": "Create Site Config",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteConfigSite",
        "tags": [
          "siteConfig"
        ],
        "summary": "Delete Site Config",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/sites/{site}/robots.txt": {
      "get": {
        "operationId": "getConfigSiteRobots",
        "tags": [
          "siteConfig"
        ],
        "summary": "Read Site robots.txt Config",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateConfigSiteRobots",
        "tags": [
          "siteConfig"
        ],
        "summary": "Update Site robots.txt Config.",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/sites/{site}/tokens.json": {
      "get": {
        "operationId": "listSiteTokens",
        "tags": [
          "siteConfig"
        ],
        "summary": "List access tokens",
        "description": "Returns the access tokens",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateSiteToken",
        "tags": [
          "siteConfig"
        ],
        "summary": "Create new access token",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/sites/{site}/tokens/${id}.json": {
      "get": {
        "operationId": "readSiteToken",
        "tags": [
          "siteConfig"
        ],
        "summary": "Read access token",
        "description": "Returns the access token",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteSiteToken",
        "tags": [
          "siteConfig"
        ],
        "summary": "Delete access token",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/sites/{site}/secrets.json": {
      "get": {
        "operationId": "listSiteSecrets",
        "tags": [
          "siteConfig"
        ],
        "summary": "List site secrets",
        "description": "Returns the site secrets",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "createSiteSecret",
        "tags": [
          "siteConfig"
        ],
        "summary": "Create new site secret",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/sites/{site}/secrets/${id}.json": {
      "get": {
        "operationId": "readSiteSecret",
        "tags": [
          "siteConfig"
        ],
        "summary": "Read secret",
        "description": "Returns the secret",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteSiteSecret",
        "tags": [
          "siteConfig"
        ],
        "summary": "Delete site secret",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/sites/{site}/apiKeys.json": {
      "get": {
        "operationId": "listSiteApiKeys",
        "tags": [
          "siteConfig"
        ],
        "summary": "List site admin API keys",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "createSiteApiKey",
        "tags": [
          "siteConfig"
        ],
        "summary": "Create or import site admin API key",
        "description": "Creates a new admin API key for the site config. If a `jwt` parameter is given, it imports the given key. Please note that the added key can immediately be used and does not need to be added to the `access.admin.apiKeys` property.\n",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/sites/{site}/apiKeys/${id}.json": {
      "get": {
        "operationId": "readSiteApiKey",
        "tags": [
          "siteConfig"
        ],
        "summary": "Read site admin API key",
        "description": "Returns the admin API key",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteSiteAdminApiKey",
        "tags": [
          "siteConfig"
        ],
        "summary": "Delete site admin API key",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/aggregated/{site}.json": {
      "get": {
        "operationId": "getAggregatedConfigSite",
        "tags": [
          "siteConfig"
        ],
        "summary": "Read Aggregated Site Config",
        "description": "Returns the aggregated site level configuration. This includes the inherited values from the profile.\n",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      }
    },
    "/config/{org}/profiles.json": {
      "get": {
        "operationId": "getConfigProfiles",
        "tags": [
          "profileConfig"
        ],
        "summary": "List Profile Config",
        "description": "Returns the configuration profile names.",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      }
    },
    "/config/{org}/profiles/{profile}.json": {
      "get": {
        "operationId": "getConfigProfile",
        "tags": [
          "profileConfig"
        ],
        "summary": "Read Profile Config",
        "description": "Returns the Profile level configuration.",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateConfigProfile",
        "tags": [
          "profileConfig"
        ],
        "summary": "Update Profile Config",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      },
      "put": {
        "operationId": "createConfigProfile",
        "tags": [
          "profileConfig"
        ],
        "summary": "Create Profile Config",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteConfigProfile",
        "tags": [
          "profileConfig"
        ],
        "summary": "Delete Profile Config",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/profiles/{profile}/robots.txt": {
      "get": {
        "operationId": "getConfigProfileRobots",
        "tags": [
          "profileConfig"
        ],
        "summary": "Read Profile robots.txt Config",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateConfigProfileRobots",
        "tags": [
          "profileConfig"
        ],
        "summary": "Update Profile robots.txt Config.",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/profiles/{profile}/tokens.json": {
      "get": {
        "operationId": "listProfileTokens",
        "tags": [
          "profileConfig"
        ],
        "summary": "List access tokens",
        "description": "Returns the access tokens",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateProfileToken",
        "tags": [
          "profileConfig"
        ],
        "summary": "Create new access token",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/profiles/{profile}/tokens/${id}.json": {
      "get": {
        "operationId": "readProfileToken",
        "tags": [
          "profileConfig"
        ],
        "summary": "Read access token",
        "description": "Returns the access token",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteProfileToken",
        "tags": [
          "profileConfig"
        ],
        "summary": "Delete access token",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/profiles/{profile}/secrets.json": {
      "get": {
        "operationId": "listProfileSecrets",
        "tags": [
          "profileConfig"
        ],
        "summary": "List profile secrets",
        "description": "Returns the profile secrets",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "createProfileSecret",
        "tags": [
          "profileConfig"
        ],
        "summary": "Create new profile secret",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/profiles/{profile}/secrets/${id}.json": {
      "get": {
        "operationId": "readProfileSecret",
        "tags": [
          "profileConfig"
        ],
        "summary": "Read secret",
        "description": "Returns the secret",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteProfileSecret",
        "tags": [
          "profileConfig"
        ],
        "summary": "Delete profile secret",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/profiles/{profile}/apiKeys.json": {
      "get": {
        "operationId": "listProfileApiKeys",
        "tags": [
          "profileConfig"
        ],
        "summary": "List profile admin API keys",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "createProfileApiKey",
        "tags": [
          "profileConfig"
        ],
        "summary": "Create or import profile admin API key",
        "description": "Creates a new admin API key for the profile config. If a `jwt` parameter is given, it imports the given key. Please note that the added key can immediately be used and does not need to be added to the `access.admin.apiKeys` property.\n",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/profiles/{profile}/apiKeys/${id}.json": {
      "get": {
        "operationId": "readProfileApiKey",
        "tags": [
          "profileConfig"
        ],
        "summary": "Read profile admin API key",
        "description": "Returns the admin API key",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteProfileAdminApiKey",
        "tags": [
          "profileConfig"
        ],
        "summary": "Delete profile admin API key",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/sites/{site}/content/query.yaml": {
      "get": {
        "operationId": "getIndexConfig",
        "tags": [
          "indexConfig"
        ],
        "summary": "Read Index Configuration",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateIndexConfig",
        "tags": [
          "indexConfig"
        ],
        "summary": "Update Index Configuration",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      },
      "put": {
        "operationId": "createIndexConfig",
        "tags": [
          "indexConfig"
        ],
        "summary": "Create Index Configuration",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteIndexConfig",
        "tags": [
          "indexConfig"
        ],
        "summary": "Delete Index Configuration",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    },
    "/config/{org}/sites/{site}/content/sitemap.yaml": {
      "get": {
        "operationId": "getSitemapConfig",
        "tags": [
          "sitemapConfig"
        ],
        "summary": "Read Sitemap Configuration",
        "security": [
          {
            "AuthCookie": [
              "config:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "updateSitemapConfig",
        "tags": [
          "sitemapConfig"
        ],
        "summary": "Update Sitemap Configuration",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      },
      "put": {
        "operationId": "createSitemapConfig",
        "tags": [
          "sitemapConfig"
        ],
        "summary": "Create Sitemap Configuration",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteSitemapConfig",
        "tags": [
          "sitemapConfig"
        ],
        "summary": "Delete Sitemap Configuration",
        "security": [
          {
            "AuthCookie": [
              "config:write"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "AuthCookie": {
        "type": "apiKey",
        "in": "cookie",
        "name": "auth_token"
      },
      "BearerToken": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "x-tagGroups": [
    {
      "name": "Authoring and Publishing",
      "tags": [
        "status",
        "publish",
        "preview",
        "code",
        "cache",
        "index",
        "sitemap",
        "snapshot"
      ]
    },
    {
      "name": "Operations",
      "tags": [
        "authentication",
        "log",
        "job"
      ]
    },
    {
      "name": "Configuration Management",
      "tags": [
        "orgConfig",
        "siteConfig",
        "profileConfig",
        "indexConfig",
        "sitemapConfig"
      ]
    }
  ]
}